functionsDirectory = "C:\\recovery-office\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\recovery-office\\build"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
base = "C:\\recovery-office"
functions = "C:\\recovery-office\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "8"
SKIP_TYPESCRIPT_CHECK = "true"
TSC_COMPILE_ON_ERROR = "true"
CI = "false"
DISABLE_ESLINT_PLUGIN = "true"
PUBLIC_URL = "/"

[build.processing]
skip_processing = true

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
Cache-Control = "public, max-age=31536000, immutable"
Content-Encoding = "gzip, br"
Link = "<https://fonts.googleapis.com>; rel=preconnect, <https://fonts.gstatic.com>; rel=preconnect; crossorigin, <https://www.google-analytics.com>; rel=dns-prefetch, <https://www.googletagmanager.com>; rel=dns-prefetch"

[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable, public, max-age=31536000, immutable"
Content-Type = "text/javascript; charset=utf-8, text/css; charset=utf-8, image/jpeg, image/png, image/svg+xml, image/webp"

[[headers]]
for = "/assets/fonts/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/api/*"

[headers.values]
Cache-Control = "public, max-age=300"

[[headers]]
for = "/locales/*"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/manifest.json"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/favicon.*"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com https:;"

[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "text/javascript; charset=utf-8"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "*.jpg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "image/jpeg"

[[headers]]
for = "*.png"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "image/png"

[[headers]]
for = "*.svg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "image/svg+xml"

[[headers]]
for = "*.webp"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "image/webp"

[[headers]]
for = "*.woff2"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"
Content-Type = "font/woff2"

[[headers]]
for = "/locales/*"

[headers.values]
Cache-Control = "public, max-age=86400"
Content-Type = "application/json; charset=utf-8"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/services"
to = "/.netlify/functions/services"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/clients"
to = "/.netlify/functions/clients"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/bookings"
to = "/.netlify/functions/bookings"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/dashboard/*"
to = "/.netlify/functions/dashboard"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/health"
to = "/.netlify/functions/health"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]