[build]
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  SKIP_TYPESCRIPT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  PUBLIC_URL = "/"

# Redirect all routes to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Asset caching rules
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Content Security Policy and other security headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade" 