[build]
  base = "."
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  SKIP_TYPESCRIPT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  PUBLIC_URL = "/"

# API proxy to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Specific API routes
[[redirects]]
  from = "/api/services"
  to = "/.netlify/functions/services"
  status = 200

[[redirects]]
  from = "/api/clients"
  to = "/.netlify/functions/clients"
  status = 200

[[redirects]]
  from = "/api/bookings"
  to = "/.netlify/functions/bookings"
  status = 200

[[redirects]]
  from = "/api/dashboard/*"
  to = "/.netlify/functions/dashboard"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# Redirect all other routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for financial services
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com https:;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 